# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("Smallest works properly and show error if needed", {
  expect_equal(Smallest(rbind(c(1,2),c(2,3),c(2,3),c(7,8))),c(1,2))
})

# Test with your dataset in "inst/"
datafile=system.file("M64.RData",package="grouptheory")
load(datafile)
# Apply test on my function
test_that("Smallest works properly with internal dataset", {
  expect_equal(Smallest(M64),c(1,2,4,8,16,32,7,1,1))
})
