# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("FindRows works properly and show error if needed", {
  expect_equal(FindRows(c(2,3,5),rbind(c(1,2,7),c(2,3,5),c(2,3,-10),c(7,8,5))),c(2,3))
  expect_error(FindRows("text"))
})

# Test with your dataset in "inst/"
datafile=system.file("M64.RData",package="grouptheory")
load(datafile)
# Apply test on my function
test_that("FindRows works properly with internal dataset", {
  expect_equal(FindRows(c(1,2,4,8,16,32,7,1,1),M64),1)
})
