# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("Occurrences works properly and show error if needed", {
  expect_true(Occurrences(c(2,3),rbind(c(1,2),c(2,3),c(2,3),c(7,8)))==2)
  expect_true(Occurrences(c(2,3),rbind(c()))==0)
  expect_error(Occurrences("text"))
})

# Test with your dataset in "inst/"
datafile=system.file("M64.RData",package="grouptheory")
load(datafile)
# Apply test on my function
test_that("Occurrences works properly with internal dataset", {
  expect_equal(Occurrences(c(1,2,4,8,16,32,7,1,1),M64),1)
})
