# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' AfromM2
#'
#' @param M,silent A list of square matrices "M" with the Identity as its first matrix and an option
#'
#' @return
#' The Cayley table "A" of the Matrix group "M"
#' @export
#'
AfromM2=function(M,silent=T){
  lM=length(M); A=c()
  woo=function(i,j){
    A=M[[i]]%*%M[[j]]
    for(s in 1:lM){
      if(sum((A-M[[s]])^2)<0.05){a=s;break}
    }
    return(a)
  }
  wo=function(i){
    woi=function(j){return(woo(i,j))}
    return(unlist(parallel::mclapply(c(1:lM),woi,mc.cores=parallel::detectCores())))
  }
  for(i in 1:lM){
    A=rbind(A,wo(i))
    if(silent==F){print(i/lM)}
  }
  return(A)
}
#list(rbind(c(1,0,0),c(0,1,0),c(0,0,1)),rbind(c(1,0,0),c(0,0,1),c(0,1,0)),rbind(c(0,1,0),c(1,0,0),c(0,0,1)),rbind(c(0,1,0),c(0,0,1),c(1,0,0)),rbind(c(0,0,1),c(1,0,0),c(0,1,0)),rbind(c(0,0,1),c(0,1,0),c(1,0,0)))
