# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' AfromM
#'
#' @param M A list of square matrices "M" with the Identity as its first matrix
#'
#' @return
#' The Cayley table "A" of the Matrix group "M"
#' @export
#'
AfromM=function(M){
  lM=length(M)
  wo=function(i){
    Mi=M[[i]]; out=c()
    for(j in 1:lM){
      A=Mi%*%M[[j]]
      for(s in 1:lM){
        if(sum((A-M[[s]])^2)<0.05){a=s;break}
      }
      out=c(out,a); rm(a)
    }
    return(out)
  }
  A=matrix(unlist(parallel::mclapply(c(1:lM),wo,mc.cores=parallel::detectCores())),byrow=T,nrow=lM,ncol=lM)
  return(A)
}
