# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Conjugates
#'
#' @param A,I,w The Cayley table "A" of a group, the list of inverses "I", and a sequence of elements "w".
#'
#' @return
#' A matrix whose rows are the different collections of elements in "A" conjugate to "w".
#' @export
#'
Conjugates=function(A,I,w){
  n=nrow(A)
  out=rbind(w)
  for(g in 2:n){
    out=rbind(out,sort(A[g,A[w,I[g]]]))
  }
  out=unique(out)
  return(out)
}
