# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Divisors
#'
#' @param n A natural number "n".
#'
#' @return
#' The divisors of "n" except 1.
#' @export
#'
#' @examples
#' Divisors(12)
Divisors=function(n){
  out=c()
  for(j in 2:n){if(n%%j==0){out=c(out,j)}}
  return(out)
}
