# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Efromv
#'
#' @param v a list of primes
#'
#' @return
#' t
#' @export
#'
Efromv=function(v){
  l=length(v); E=matrix(rep(0,l^2),nrow=l,ncol=l)
  for(i in 1:l){
    for(j in 1:l){
      if(relx(v[i],v[j])){E[j,i]=1}
    }
  }
  return(E)
}
