# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Efromx
#'
#' @param x a natural number
#'
#' @return
#' t
#' @export
#'
Efromx=function(x){return(Efromv(PrimeFactors(x)))}
