# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' FindRows
#'
#' @param v,M A row vector "v" and a Matrix "M".
#'
#' @return
#' The indices of all the rows of "M" approximately equal to "v". The comparison is made only where "M" is non-negative.
#' @export
#'
#' @examples
#' FindRows(c(2,3,5),rbind(c(1,2,7),c(2,3,5),c(2,3,-10),c(7,8,5)))
#'
#' # Example with your dataset in "inst/"
#' datafile=system.file("M64.RData",package="grouptheory")
#' load(datafile)
#' # Apply my function
#' FindRows(c(1,2,4,8,16,32,7,1,1),M64)
FindRows=function(v,M){
  l=length(v); ll=ncol(M); out=c()
  if(l==ll){
    for(j in 1:nrow(M)){
      Mj=M[j,]; Dj=abs(Mj-v); Dj=Dj[Mj>=0]
      if(sum(Dj)<0.5){out=c(out,j)}
    }
  }
  return(out)
}
