# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Inverse
#'
#' @param A The Cayley table "A" of a group
#'
#' @return
#' The vector with the inverse of all the elements in the group.
#' @export
#'
Inverse=function(A){
  n=nrow(A); I=c(1)
  for(j in 2:n){
    I=c(I,which(A[j,]==1))
  }
  return(I)
}
