# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Is1Number
#'
#' @param x A natural number x
#'
#' @return
#' 1 if there is only one group of order x, 0 otherwise
#' @export
#'
Is1Number=function(x){
  v=PrimeFactors(x); u=unique(v); out=1
  if(length(v)!=length(u)){out=0}
  else{
    if(length(remov(x))>0){out=0}
  }
  return(out)
}
