# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Is2Number
#'
#' @param x A natural number
#'
#' @return
#' 1 or 2 if there are exactly two groups of order x, 0 otherwise.
#' @export
#'
Is2Number=function(x){
  v=PrimeFactors(x); u=unique(v); out=0
  if(length(v)==length(u)){
    if(length(remov(x))==2){out=1}
  }
  if(length(u)==length(v)-1){
    E=Efromv(u)
    if(sum(E)==0){
      fr=unlist(lapply(v,function(x){return(length(which(v==x)))}))
      p=v[fr==2][1]; s=0
      for(j in 1:length(u)){
        if(p!=u[j] & rel(p^2,u[j])==1){s=s+1}
      }
      if(s==0){out=2}
    }
  }
  return(out)
}
