# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Is1Number
#'
#' @param x A natural number
#'
#' @return
#' 1 if there is only one group of order x, 0 otherwise
#' @export
#'
Is3Number=function(x){
  v=PrimeFactors(x); u=unique(v); out=0
  if(length(v)==length(u)){
    uu=remov(x)
    if(length(uu)==3){
      if(sum(abs(Efromv(uu)-rbind(c(0,0,0),c(1,0,0),c(0,1,0))))==0){out=1}
    }
  }
  if(length(u)==length(v)-1){
    E=Efromv(u)
    if(sum(E)==0){
      fr=unlist(lapply(v,function(x){return(length(which(v==x)))}))
      p=v[fr==2][1]; s=0
      for(j in 1:length(u)){
        if(p!=u[j] & rel(p^2,u[j])==1){s=s+1}
      }
      if(s==1){out=2}
    }
  }
  return(out)
}
