# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' IsAbelian
#'
#' @param A The Cayley table "A" of a group
#'
#' @return
#' 1 if the group is Abelian 0 otherwise.
#' @export
#'
IsAbelian=function(A){
  out=0
  if(sum((A-t(A))^2)<0.5){out=1}
  return(out)
}
