# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' YNamesfromY
#'
#' @param Y The matrix group "M", its Cayley table "A", and its list of up-to-conjugacy-subgroups "X".
#'
#' @return The names of the groups
#' 
#' @export
#'
NamesfromY=function(Y){
  out=c()
  for(j in 1:nrow(Y)){
    size=Y[j,1]; type=Y[j,2]
    if(type==0 | type== -100){out=c(out,paste0(size,".?","(",j,")"))}
    if(type>0){out=c(out,paste0(size,".",type,"(",j,")"))}
    if(size==21 & type==-4){out=c(out,paste0("21.1","(",j,")"))}
    if(type==-3){out=c(out,paste0("D",size,"(",j,")"))}
    if(size==4 & type==-2){out=c(out,paste0("K",4,"(",j,")"))}
    if(size==9 & type==-2){out=c(out,paste0("Z3^2","(",j,")"))}
    if(type==-1){out=c(out,paste0("Z",size,"(",j,")"))}
    
  }
  return(out)
}
