# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' NumberOfSubgroups
#'
#' @param A The Cayley table "A" of a group
#'
#' @return
#' A couple with the number of subgroups up to conjugacy and overall.
#' @export
#'
NumberOfSubgroups=function(A){
  X=XfromA(A); l=length(X); s=0
  for(j in 1:l){s=s+X[[j]][2]}
  return(c(l,s))
}
