# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Occurrences
#'
#' @param v,M A matrix "M" and a row vector "v".
#'
#' @return
#' The number of times "v" is a row vector of "M".
#' @export
#'
#' @examples
#' Occurrences(c(2,3),rbind(c(1,2),c(2,3),c(2,3),c(7,8)))
#'
#' # Example with your dataset in "inst/"
#' datafile=system.file("M64.RData",package="grouptheory")
#' load(datafile)
#' # Apply my function
#' Occurrences(c(1,2,4,8,16,32,7,1,1),M64)
Occurrences=function(v,M){
  l=length(v)
  for(s in 1:l){
    a=M[,s]
    ind=which(a==v[s])
    M=rbind(M[ind,])
  }
  return(length(ind))
}
