# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' OrderStructure
#'
#' @param A The Cayley table "A" of a group.
#'
#' @return
#' The number of elements of each possible orders except one. That is of each non-one divisor of the size of the group.
#' @export
#'
OrderStructure=function(A){
  l=nrow(A)
  ord=c()
  for(j in 2:l){
    a=j
    for(s in 1:l){
      if(a==1){break}
      a=A[j,a]
    }
    ord=c(ord,s)
  }
  out=c()
  for(s in 2:l){
    if(l%%s==0){
      out=c(out,length(which(ord==s)))
    }
  }
  return(out)
}
