# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' PrimeFactors
#'
#' @param x A natural number x
#'
#' @return
#' All its divisors of the form p^k
#' @export
#'
PrimeFactors=function(x){
  if(x==1){factors=c(1)}
  else{
  i=2; factors=c()
  while(x>=i){
    if(! x %% i){
      factors=c(factors,i)
      x=x/i
      i=i-1
    }
    i=i+1
  }
  }
  return(factors)
}
