# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' rel
#'
#' @param p,q two natural numbers
#'
#' @return
#' t
#' @export
#'
rel=function(p,q){
  out=0
  if(relx(p,q)==1 | relx(q,p)==1){out=1}
  return(out)
}
