# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Relabel
#'
#' @param A,w The Cayley table "A" of a group and a vector "w" of elements in a subgroup
#'
#' @return
#' The Cayley table "A" of the subgroup.
#' @export
#'
Relabel=function(A,w){
  l=length(w)
  Aw=A[w,w]; m=Aw[1,]
  fu=function(i){return(which(m==i))}
  return(apply(Aw,c(1,2),fu))
}
