# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' relx
#'
#' @param p,q two natural numbers
#'
#' @return
#' t
#' @export
#'
relx=function(p,q){
  out=0
  if(q-p*floor(q/p)==1){out=1}
  return(out)
}
