# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' remov
#'
#' @param x a natural number
#'
#' @return
#' t
#' @export
#'
remov=function(x){
  v=PrimeFactors(x); E=Efromv(v); ind=c()
  for(j in 1:length(v)){
    if(length(v[v==v[j]])==1 & sum(E[j,])==0 & sum(E[,j])==0){ind=c(ind,j)}
  }
  if(length(ind)>0){out=v[-ind]}
  else{out=v}
  return(out)
}
