# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Smallest
#'
#' @param M A matrix "M".
#'
#' @return
#' The smallest row of "M" in lexicographical order.
#' @export
#'
#' @examples
#' Smallest(rbind(c(1,2),c(2,3),c(2,3),c(7,8)))
#'
#' # Example with your dataset in "inst/"
#' datafile=system.file("M64.RData",package="grouptheory")
#' load(datafile)
#' # Apply my function
#' Smallest(M64)
Smallest=function(M){
  n=ncol(M)
  for(j in 1:n){
    if(nrow(M)>1){
      x=M[,j]
      ind=which(x==min(x))
      M=rbind(M[ind,])
    }
  }
  return(M[1,])
}
