# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Span
#'
#' @param A,w The Cayley table "A" of a group and a vector "w" of elements in the group
#'
#' @return
#' The vector of elements in the subgroup of "A" generated by "w".
#' @export
#'
Span=function(A,w){
  n=nrow(A); a=unique(c(1,w))
  for(s in 1:n){
    an=unique(sort(A[a,a]))
    if(length(an)==length(a)){
      a=an
      break
    }
    a=an
  }
  return(a)
}
