# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' XfromA
#'
#' @param A,silent The Cayley table "A" of a group and a parameter
#'
#' @return
#' A list of all the subgroups of "A" up to conjugacy. Each element of the list is a vector containing 1. its size, 2. its occurrences, 3. its rank ie the minimal size of a generating set, 4. the vector of the elements of one of its representatives.
#' @export
#'
XfromA=function(A,silent=T){
  NewPart=function(A,B){
    C=c()
    if(length(B)>0 & length(A)>0){
      for(i in 1:length(A)){
        a=A[[i]]; s=1
        for(j in 1:length(B)){
          b=B[[j]]
          if(length(a[-3])==length(b[-3])){if(sum((a[-3]-b[-3])^2)==0){s=0; break}}
        }
        if(s==1){C[[length(C)+1]]=a}
      }
    }
    else{C=A}
    return(C)
  }
  up=function(A,IA,O1,neworder){
    n=nrow(A); L=Divisors(n); ind=c(1:n); ii=length(O1)
    upsmall=function(i){
      O2=list(); oi=O1[[i]][-c(1:3)]
      for(l in L){assign(as.matrix(paste0("W",l)),rbind(c()))}
      if(length(oi<n)){
        for(j in ind[-oi]){
          w=Span(A,sort(c(oi,j))); l=length(w)
          assign(paste0("W",l),rbind(get(paste0("W",l)),w))
        }
      }
      for(l in L){
        if(length(get(paste0("W",l)))>0){
          W=unique(get(paste0("W",l))); V=c()
          for(j in 1:nrow(W)){
            w=W[j,]
            if(Occurrences(w,V)==0){
              Z=Conjugates(A,IA,w); V=rbind(V,Z)
              O2[[length(O2)+1]]=c(l,nrow(Z),neworder,Smallest(Z))
            }
          }
        }
      }
      for(l in L){rm(list=paste0("W",l))}
      return(O2)
    }
    return(unique(unlist(parallel::mclapply(c(1:ii),upsmall,mc.preschedule=F,mc.cores=parallel::detectCores()),recursive=F)))
  }
  
  IA=Inverse(A); out=1; X0=list(c(1,1,0,1)); if(silent==F){print(c(0,length(X0)))}
  X1=up(A,IA,X0,1); if(silent==F){print(c(1,length(X1)))}
  XX=append(X0,X1)
  for(s in 2:10){
    assign(paste0("X",s),up(A,IA,get(paste0("X",s-1)),s))
    for(j in 1:(s-1)){
      assign(paste0("X",s),NewPart(get(paste0("X",s)),get(paste0("X",s-j))))
      if(length(get(paste0("X",s)))==0){break}
    }
    l=length(get(paste0("X",s)))
    if(l==0){break}
    if(silent==F){print(c(s,l))}
    XX=append(XX,get(paste0("X",s)))
  }
  return(XX)
}
