# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' YfromMAX
#'
#' @param M,A,X The matrix group "M", its Cayley table "A", and its list of up-to-conjugacy-subgroups "X".
#'
#' @return A list of identifiers of the groups
#' 
#' @export
#'
YfromMAX=function(M,A,X){
  dd=c(); n=nrow(M[[1]]); mid=-1
  for(j in 1:length(M)){
    if(det(M[[j]])<0){dd=c(dd,j)}
    if(sum((M[[j]]+diag(rep(1,n)))^2)<0.01){mid=j}
  }
  ox=c()
  for(j in 1:length(X)){#print(j)
    w=X[[j]]; x=w[3]; ww=w[-c(1,2,3)]; o1=o2=0
    if(length(intersect(ww,dd))>0){o1=1}
    if(length(intersect(ww,mid))>0){o2=1}
    type=GroupId(A,ww,x)
    ox=rbind(ox,c(w[1],type,w[2],x,o1,o2))
  }
  return(ox)
}
